### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by efouts** [Qualtrax/lastpublishedrevision.com#2]
@kevPo I got a few pieces of feedback from our presentation this morning. We should act on these before the blog goes out Friday.
- Link to support portal
- Badge looks like a button
- Needs a stronger Qualtrax branding (We should ask @sobenauer for advice)

**Comment by efouts** [comment]
Patrick suggested some kind of footer. That may knock all the first and last items.

**Comment by efouts** [comment]
Making the badge a link to the downloads page when it is just released could be a good idea. If you wanted to add an icon to it these may work.

Just Released:
glyphicon glyphicon-download
glyphicon glyphicon-tag

About to Release:
glyphicon glyphicon-time

**Comment by kevPo** [comment]
- [x] Add footer with links to support site, downloads page, Qualtrax blog, and Qualtrax site.
- [x] Add emoji to released badge.
